# Generated by Django 3.2.6 on 2021-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('queries', models.CharField(choices=[('P', 'Personal Question'), ('S', 'Site Bugs'), ('A', 'About Books'), ('AS', 'About Our Services'), ('O', 'Other')], max_length=2)),
                ('tell_us', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
