# Generated by Django 3.2.6 on 2021-08-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_signup_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='create',
            new_name='create1',
        ),
    ]
