# Generated by Django 3.2.6 on 2021-08-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_signup_create1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='create1',
        ),
    ]
