# Generated by Django 3.2.6 on 2021-08-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_signup_create1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
